FROM alpine:3.20

WORKDIR /app

COPY script.sh .

RUN apk add --no-cache curl && \
    adduser -D nonrootuser && \
    chown -R nonrootuser:nonrootuser .

USER nonrootuser

CMD ["./script.sh"]

# Improved Dockerfile for exercise 1.7 
# (also added shebang to script.sh, so shell form CMD is not needed)