version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile-1.14-back
    ports:
      - 127.0.0.1:8080:8080

  frontend:
    build:
      dockerfile: Dockerfile-1.14-front
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - backend

  redis:
    image: redis:alpine
    restart: unless-stopped
