FROM golang:1.22-alpine AS builder

EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5000

WORKDIR /app

COPY ./material-applications/example-backend .

RUN CGO_ENABLED=0 GOOS=linux go build -o server . && \
    echo "nonrootuser:x:10001:10001:App User:/:/sbin/nologin" > /etc/passwd


FROM scratch

COPY --from=builder /app/server .

COPY --from=builder /etc/passwd /etc/passwd

USER nonrootuser

CMD ["./server"]

# Image size for this Dockerfile: 19MB
