FROM golang:1.16-alpine

EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5000

WORKDIR /app

COPY ./material-applications/example-backend .

RUN go build
RUN adduser -D nonrootuser
RUN chown -R nonrootuser:nonrootuser .

USER nonrootuser

CMD ./server
