version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile-1.14-back
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres

  frontend:
    build:
      dockerfile: Dockerfile-1.14-front
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - backend

  redis:
    image: redis:alpine
    restart: unless-stopped
    depends_on:
      - backend

  database:
    image: postgres:alpine
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - backend
