version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile-1.14-back
    ports:
      - 8080:8080

  frontend:
    build:
      dockerfile: Dockerfile-1.14-front
    ports:
      - 5000:5000
    depends_on:
      - backend
